# Generated by Django 4.0.4 on 2022-10-23 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work_status', '0002_progress_task_rename_departments_cg_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cg',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
